### PR TITLE
Migrate from PSR-0 to PSR-4

### PR DESCRIPTION
**Pull request by KennedyTedesco**
PSR-0 is depreciated and will eventually be removed by composer.

### CODE REVIEW

**Comment by danizord** [comment]
Just a side note: PSR-0 is not depreciated and will not be removed by Composer ;)

**Comment by KennedyTedesco** [comment]
You are right. But, like i said, i think eventually will be. PSR-4 fixes a lot of problems. Doesn't make sense to keep both in the future. (Just a personal opinion).

A good point: http://philsturgeon.uk/blog/2014/07/send-psr0-to-the-standards-farm-in-the-sky

**Comment by lcobucci** [comment]
A :beer: for you @KennedyTedesco!

**Comment by KennedyTedesco** [comment]
Cheers, :beers: @lcobucci!

**Comment by KennedyTedesco** [comment]
image

Finally. It's a good thing. But, like @danizord said, it will not be removed (cannot be, not so soon).

**Pull request merged**
